apiVersion: v1
kind: ServiceAccount
metadata:
  name: ws-gateway
  namespace: test-runners
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ws-gateway-role
  namespace: test-runners
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ws-gateway-rolebinding
  namespace: test-runners
subjects:
- kind: ServiceAccount
  name: ws-gateway
  namespace: test-runners
roleRef:
  kind: Role
  name: ws-gateway-role
  apiGroup: rbac.authorization.k8s.io

